# Example Wikibase docker-compose setup
version: '3.4'

x-common-variables: &wikibase_variables
  DB_SERVER: mysql.svc:3306
  MW_ADMIN_NAME: admin
  MW_ADMIN_PASS: change-this-password
  MW_ADMIN_EMAIL: admin@example.com
  MW_WG_SECRET_KEY: some-secret-key
  # Disable jobs running after requests when wikibase_jobrunner is defined
  MW_WG_JOB_RUN_RATE: 0
  DB_USER: sqluser
  DB_PASS: change-this-sqlpassword
  DB_NAME: my_wiki
  WIKIBASE_HOST: localhost
  BOTUSER_NAME: botuser_name
  BOTUSER_PW: botuser_pw
x-extra-variables: &wikibase_extra_variables
  MW_ELASTIC_HOST: elasticsearch.svc
  MW_ELASTIC_PORT: 9200

services:
  importer:
    build: .
    container_name: mardi-importer
    volumes:
      - shared_mardi_wikibase:/shared/:ro
      - ./src:/importer/src # for development
      - ./tests:/tests # for development
      - ./config/:/config
    links:
      - wikibase
    depends_on:
      - wikibase
    environment:
      <<: *wikibase_variables
      DB_HOST: mardi-mysql
      IMPORTER_CRON_ENABLE: ${IMPORTER_CRON_ENABLE:-false}

  wikibase:
    image: "ghcr.io/mardi4nfdi/docker-wikibase:main"
    container_name: mardi-wikibase
    links:
      - mysql
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      ## This shares the configuration with jobrunner and the importer
      - shared_mardi_wikibase:/var/www/html/:rw
      - ./mediawiki/LocalSettings.d:/shared/LocalSettings.d
      - ./mediawiki/LocalSettings.d:/var/www/html/LocalSettings.d
      - ./mediawiki/images/:/var/www/html/images/
    networks:
      default:
        aliases:
         - wikibase-docker.svc
         - wikibase.svc
    environment:
      <<: *wikibase_variables
      WIKIBASE_PINGBACK:
      MW_WG___UPLOADS:
      <<: *wikibase_extra_variables
    ports:
      - 8080:80

  wikibase_jobrunner:
    image: "ghcr.io/mardi4nfdi/docker-wikibase:main"
    entrypoint: /bin/bash
    command:  /jobrunner-entrypoint.sh
    links:
      - mysql
    depends_on:
      - mysql
    restart: always
    volumes:
      - shared_mardi_wikibase:/shared/
      - ./mediawiki/LocalSettings.d:/shared/LocalSettings.d:ro
      - ./mediawiki/jobrunner-entrypoint.sh:/jobrunner-entrypoint.sh
    networks:
      default:
        aliases:
          - wikibase-jobrunner.svc
    environment:
      <<: *wikibase_variables
      MAX_JOBS: 1
      <<: *wikibase_extra_variables

  mysql:
    image: "mariadb:10.3"
    container_name: mardi-mysql
    restart: unless-stopped
    volumes:
      - mediawiki-mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: sqluser
      MYSQL_PASSWORD: change-this-sqlpassword
      WIKIBASE_HOST: localhost
      MYSQL_DATABASE: my_wiki
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    networks:
      default:
        aliases:
         - mysql.svc

  elasticsearch:
    image: "${ELASTICSEARCH_IMAGE_NAME:-wikibase/elasticsearch:6.8.23-wmde.6}"
    restart: unless-stopped
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      default:
        aliases:
         - elasticsearch.svc
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  wdqs-frontend:
    image: "${WDQS_FRONTEND_IMAGE_NAME:-wikibase/wdqs-frontend:wmde.6}"
    container_name: mardi-wdqs-frontend
    restart: unless-stopped
    ports:
    # CONFIG - Change the 8282 here to expose the Query Service UI on a different port
     - "8282:80"
    depends_on:
    - wdqs-proxy
    networks:
      default:
        aliases:
         - query.portal.mardi4nfdi.de
         - wdqs-frontend.svc
    environment:
      - WIKIBASE_HOST=wikibase.svc
      - WDQS_HOST=wdqs-proxy.svc
      - BRAND_TITLE=MaRDIQueryService

  wdqs:
    image: "${WDQS_IMAGE_NAME:-wikibase/wdqs:0.3.40-wmde.6}"
    container_name: mardi-wdqs
    restart: unless-stopped
    volumes:
      - query-service-data:/wdqs/data
    command: /runBlazegraph.sh
    networks:
      default:
        aliases:
         - wdqs.svc
    environment:
      - WIKIBASE_HOST=wikibase.svc
      - WDQS_HOST=wdqs.svc
      - WDQS_PORT=9999
    expose:
      - 9999

  wdqs-proxy:
    image: "${WDQS_PROXY_IMAGE_NAME:-wikibase/wdqs-proxy:wmde.6}"
    container_name: mardi-wdqs-proxy
    restart: unless-stopped
    environment:
      - PROXY_PASS_HOST=wdqs.svc:9999
    ports:
     - "8989:80"
    depends_on:
    - wdqs
    networks:
      default:
        aliases:
         - wdqs-proxy.svc

  wdqs-updater:
    image: "${WDQS_IMAGE_NAME:-wikibase/wdqs:0.3.40-wmde.6}"
    container_name: mardi-wdqs-updater
    restart: unless-stopped
    command: /runUpdate.sh
    depends_on:
    - wdqs
    - wikibase
    networks:
      default:
        aliases:
         - wdqs-updater.svc
    environment:
     - WIKIBASE_HOST=wikibase.svc
     - WDQS_HOST=wdqs.svc
     - WDQS_PORT=9999
    
volumes:
  shared_mardi_wikibase:
  mediawiki-mysql-data:
  elasticsearch-data:
  query-service-data:

networks:                                
  default:                               
    driver: bridge                       
    driver_opts:                         
      com.docker.network.driver.mtu: 1450

